### ISSUE TITLE
Update to Compose 1.0.0-beta08 introduces bug when too many screen changes occur quickly

### ISSUE THREAD

**Issue by Zhuinden** [Zhuinden/simple-stack-compose-integration#9]
```
2021-06-04 17:09:49.968 30674-30674/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.zhuinden.simplestackcomposedogexample, PID: 30674
    java.lang.IllegalArgumentException: Invalid start index
        at androidx.compose.runtime.Pending.<init>(Composer.kt:92)
        at androidx.compose.runtime.ComposerImpl.start(Composer.kt:1852)
        at androidx.compose.runtime.ComposerImpl.startReplaceableGroup(Composer.kt:1102)
        at com.zhuinden.simplestackcomposeintegration.core.ComposeStateChanger$BackstackState.RenderScreen(ComposeIntegrationCore.kt:241)
        at com.zhuinden.simplestackcomposeintegration.core.ComposeStateChanger.RenderScreen(ComposeIntegrationCore.kt:287)
        at com.zhuinden.simplestackcomposeintegration.core.ComposeStateChanger$RenderScreen$1.invoke(Unknown Source:10)
        at com.zhuinden.simplestackcomposeintegration.core.ComposeStateChanger$RenderScreen$1.invoke(Unknown Source:10)
        at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:140)
        at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2156)
        at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(Composer.kt:2399)
        at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:2574)
        at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:2567)
        at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations(SnapshotState.kt:523)
        at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:2560)
        at androidx.compose.runtime.ComposerImpl.recompose$runtime_release(Composer.kt:2536)
        at androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:613)
        at androidx.compose.runtime.Recomposer.performRecompose(Recomposer.kt:763)
        at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:102)
        at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:446)
        at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:415)
        at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:34)
        at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.android.kt:109)
        at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:41)
        at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:69)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:964)
        at android.view.Choreographer.doCallbacks(Choreographer.java:790)
        at android.view.Choreographer.doFrame(Choreographer.java:721)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:951)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

This crash was not present before updating from 1.0.0-beta07 to 1.0.0-beta08.

**Comment by Zhuinden** [comment]
I believe this is a bug in Compose, so I opened https://issuetracker.google.com/issues/190140483

**Comment by Zhuinden** [comment]
It was a bug on my side, Compose Compiler was still beta07 for some reason
